services:
  - name: chouga-backend
    type: web
    region: sa-east-1
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true