services:
  - name: chouga-backend
    type: web
    region: sa-east-1
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_ADMIN
        value: "false"
      - key: PORT
        value: "9000"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: COOKIE_SECRET
        sync: false
    memory: 2048
    plan: starter